jee6-ejb3/src/main/java/jee6ejb/model/Personne.java
package jee6ejb.model;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.*;
import javax.persistence.Id;

@Entity
public class Personne implements Serializable {

    @Id
    @GeneratedValue(strategy = AUTO)
    private Long id;
    private String firstname;
    private String lastname;

    public Personne() {
    }

    public Personne(String firstname, String lastname) {
        this.firstname = firstname;
        this.lastname = lastname;
    }

    public Long getId() {
        return id;
    }

    public String getFirstname() {
        return firstname;
    }

    public String getLastname() {
        return lastname;
    }
}

jee6-ejb3/src/main/java/jee6ejb/jsf2examples/wizard/Step1Bean.java
package jee6ejb.jsf2examples.wizard;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ActionEvent;
import lombok.Data;
import org.slf4j.LoggerFactory;

@ManagedBean
@ViewScoped
@Data
public class Step1Bean {

    private String name;
    private String surname;
    @ManagedProperty(value = "#{wizardBean}")
    private WizardBean associatedWizard;

    public Step1Bean() {
        LoggerFactory.getLogger(Step1Bean.class).info("Created a new Step 1 Bean !");
    }

    public void tryToValidateStepAndAdvanceWizardIfOk(ActionEvent ae) {
        // Perform real save in database
        boolean success = true;

        // Is successfull, tell the wizard that we can proceed !
        if (success) {
            associatedWizard.setTransactionId("AZDDE00789");
            associatedWizard.nextStep();
        }
    }
}

jee6-ejb3/src/main/java/jee6ejb/jsf2examples/wizard/Step2Bean.java
package jee6ejb.jsf2examples.wizard;

import com.google.common.base.Predicate;
import static com.google.common.collect.Collections2.*;
import static com.google.common.collect.Lists.*;
import java.util.Arrays;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ActionEvent;
import lombok.Data;
import org.slf4j.LoggerFactory;

@ManagedBean
@ViewScoped
@Data
public class Step2Bean {

    private String number;
    private String whatever;
    @ManagedProperty(value = "#{wizardBean}")
    private WizardBean associatedWizard;

    public Step2Bean() {
        LoggerFactory.getLogger(Step2Bean.class).info("Created a new Step 2 Bean !");
    }

    public void tryToValidateStepAndAdvanceWizardIfOk(ActionEvent ae) {
        // Perform real save in database
        boolean success = true;

        // Is successfull, tell the wizard that we can proceed !
        if (success) {
            associatedWizard.nextStep();
        }
    }

    public List<String> getAllPossibleWhatever(final String query) {
        List<String> fullList = getSampleList();
        return newArrayList(
                filter(fullList, new Predicate<String>() {
            @Override
            public boolean apply(String t) {
                return t.startsWith(query);
            }
        }));
    }

    private List<String> getSampleList() {
        return Arrays.asList("AZEAZEA", "AZEAZEAZE", "SDFSZDFSDF", "ERRGBERBERB", "AZEQSDERH");
    }
}

jee6-ejb3/src/main/java/jee6ejb/jsf2examples/wizard/Step3Bean.java
package jee6ejb.jsf2examples.wizard;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.event.ActionEvent;
import lombok.Data;
import org.slf4j.LoggerFactory;

@ManagedBean
@ViewScoped
@Data
public class Step3Bean {

    @ManagedProperty(value = "#{wizardBean}")
    private WizardBean associatedWizard;

    public Step3Bean() {
        LoggerFactory.getLogger(Step3Bean.class).info("Created a new Step 3 Bean !");
    }

    public void tryToValidateStepAndAdvanceWizardIfOk(ActionEvent ae) {
        // Perform real save in database
        boolean success = true;

        // Is successfull, tell the wizard that we can proceed !
        if (success) {
            associatedWizard.nextStep();
        }
    }
}

jee6-ejb3/src/main/java/jee6ejb/jsf2examples/wizard/WizardBean.java
package jee6ejb.jsf2examples.wizard;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import lombok.Data;
import org.slf4j.LoggerFactory;

@ManagedBean
@SessionScoped
@Data
public class WizardBean {

    private static final int NOT_STARTED_STEP = 0;
    private static final int FINISHED_STEP = 4;
    private boolean currentWizardStarted;
    private boolean currentWizardCompleted;
    private int step = NOT_STARTED_STEP;

    private String transactionId;

    public void begin(ActionEvent e) {
        currentWizardStarted = true;
        nextStep();
    }

    void nextStep() {
        increaseStepByOne();
        checkWizardCompletnessAndFlagItAccordingly();
    }

    private void increaseStepByOne() {
        step++;
    }

    private void checkWizardCompletnessAndFlagItAccordingly() {
        if (step == FINISHED_STEP) {
            currentWizardCompleted = true;
        }
    }

    public void destroy(ActionEvent e){
        LoggerFactory.getLogger(WizardBean.class).info("Wizard Bean supposedly destroyed !");
        FacesContext.getCurrentInstance().getExternalContext().getSessionMap().remove("wizardBean");
    }
}

jee6-ejb3/src/main/java/jee6ejb/web/HomeBean.java
package jee6ejb.web;

import jee6ejb.model.Personne;
import jee6ejb.service.PersonneService;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.Collection;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.inject.Inject;
import org.slf4j.Logger;

@Named(value = "homeBean")
@SessionScoped
public class HomeBean implements Serializable {

    private String message = "EJB & JEE6 rocks !";
    @Inject
    private PersonneService personneService;

    @Inject
    private Logger mainLogger;

    private String firstName;
    private String lastName;

    public HomeBean() {
    }

    @PostConstruct
    void init() {
        mainLogger.info("HomeBean initialized");
        mainLogger.info("I'm gonna create some person in db...");
        createRandomPersonneInDB();
    }

    public String getMessage() {
        return message;
    }

    public Collection<Personne> getPersonnes() {
        return personneService.getAllPersonnes();
    }

    public void savePersonneInDB(ActionEvent actionEvent) {
        mainLogger.info("About to save a new Personne : {} {}", firstName, lastName);
        personneService.savePersonne(new Personne(firstName, lastName));
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("You've registered"));
    }

    private void createRandomPersonneInDB() {
        personneService.savePersonne(new Personne("Personne " + Math.random(), "" + Math.random()));
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}

jee6-ejb3/src/main/webapp/WEB-INF/templates/baseTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet library="css/bootstrap" name="bootstrap.css"/>
        <ui:insert name="styles"></ui:insert>
        <title>Facelets Template</title>
    </h:head>

    <h:body>

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">Project name</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="#">Home</a></li>
                            <li><a href="#about">About</a></li>
                            <li><a href="#contact">Contact</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <ui:insert name="container"></ui:insert>
        </div>

    </h:body>

</html>

jee6-ejb3/src/main/webapp/home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>

    </h:head>
    <h:body>
        <h1>JEE6 with EJB's and primefaces</h1>
        <h:form id="form">
            <p:dataTable id="personsTable" var="person" value="#{homeBean.personnes}">
                <f:facet name="header">  
                    Person's list 
                </f:facet>

                <p:column headerText="ID">  
                    <h:outputText value="#{person.id}" />  
                </p:column>  

                <p:column headerText="First name">  
                    <h:outputText value="#{person.firstname}" />  
                </p:column>  

                <p:column headerText="Last Name">  
                    <h:outputText value="#{person.lastname}" />  
                </p:column>  

            </p:dataTable>  

            <h2>New personne creation</h2>

            <p:panel id="panel" header="New Person" style="margin-bottom:10px;">  
                <p:messages id="messages" />  
                <h:panelGrid columns="3">  
                    <h:outputLabel for="firstname" value="Firstname: *" />  
                    <p:inputText id="firstname"   
                                 value="#{homeBean.firstName}" required="true" label="Firstname">  
                        <f:validateLength minimum="2" />  
                    </p:inputText>  
                    <p:message for="firstname" />  

                    <h:outputLabel for="surname" value="Surname: *" />  
                    <p:inputText id="surname"   
                                 value="#{homeBean.lastName}" required="true" label="Surname"/>  
                    <p:message for="surname" />  
                </h:panelGrid>  
            </p:panel>  

            <p:commandButton value="Save (ajax!)" 
                             update="panel,personsTable" 
                             id="toto"  
                             actionListener="#{homeBean.savePersonneInDB}" />
        </h:form>
    </h:body>
</html>

jee6-ejb3/src/main/webapp/wizard/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    template="./../WEB-INF/templates/baseTemplate.xhtml"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:h="http://java.sun.com/jsf/html">

    <ui:define name="styles">
        <style>
            body { padding-top: 50px; }
        </style>
    </ui:define>
    <ui:define name="container">

        <h1>Subscription</h1>
        <h:panelGroup rendered="#{!wizardBean.currentWizardStarted}">
            <h:form>
                <p>To start a new subscription process :
                    <h:commandButton value="Bein" actionListener="#{wizardBean.begin}"/>
                </p>
            </h:form>
        </h:panelGroup>

        <h:panelGroup rendered="#{wizardBean.currentWizardStarted}">
            <ui:include src="wiz-#{wizardBean.step}.xhtml" />
        </h:panelGroup>

    </ui:define>

</ui:composition>

jee6-ejb3/src/main/webapp/wizard/wiz-0.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:component
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:h="http://java.sun.com/jsf/html">
    <!-- Empty 'step 0' file as a workaround of
    http://stackoverflow.com/questions/11989631/skip-executing-uiinclude-when-parent-ui-component-is-not-rendered
    -->
</ui:component>

jee6-ejb3/src/main/webapp/wizard/wiz-1.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:component
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:h="http://java.sun.com/jsf/html">
    <h2>Identité</h2>
    <h3>Coordonnées</h3>
    <h:form id="step1Form" styleClass="form-horizontal">
        <div class="control-group">
            <label class="control-label" for="name">Nom</label>
            <div class="controls">
                <h:inputText id="name" value="#{step1Bean.name}" required="true" requiredMessage="Valeur obligatoire"/>
                <span><h:message errorStyle="color:red" for="name"/></span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="surname">Prénom</label>
            <div class="controls">
                <h:inputText id="surname" value="#{step1Bean.surname}" required="true" requiredMessage="Valeur obligatoire"/>
                <span><h:message errorStyle="error" for="surname"/></span>
            </div>
        </div>
        <div class="form-actions">
            <h:commandButton styleClass="btn" value="Sauver pour plus tard" />&#160;
            <h:commandButton styleClass="btn btn-primary" value="Suivant" actionListener="#{step1Bean.tryToValidateStepAndAdvanceWizardIfOk}"/>
        </div>
    </h:form>
</ui:component>

jee6-ejb3/src/main/webapp/wizard/wiz-2.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:component
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">
    <h2>Versement (transaction id : #{wizardBean.transactionId})</h2>
    <h:form id="step2Form">
        <p:panel header="Informations très très importantes" toggleable="true" id="panel">
            <p:autoComplete id="acSimple"
                            value="#{step2Bean.whatever}"
                            completeMethod="#{step2Bean.getAllPossibleWhatever}"/>
        </p:panel>
        <p><h:commandButton actionListener="#{step2Bean.tryToValidateStepAndAdvanceWizardIfOk}"/></p>
    </h:form>
</ui:component>

jee6-ejb3/src/main/webapp/wizard/wiz-3.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:component
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:h="http://java.sun.com/jsf/html">
    <h2>Step 3 (transaction id : #{wizardBean.transactionId})</h2>
    <h:form id="step3Form">

        <p><h:commandButton value="done!" actionListener="#{step2Bean.tryToValidateStepAndAdvanceWizardIfOk}"/></p>
    </h:form>
</ui:component>

jee6-ejb3/src/main/webapp/wizard/wiz-4.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:component
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:h="http://java.sun.com/jsf/html">
    <h2>Step 4 - Done (transaction id : #{wizardBean.transactionId})</h2>
    <h:form id="step4Form">
        <p>Congrats, you completed the survey !</p>
        <p>Here is a quick recap of your informations ...</p>

        <p><h:commandButton value="Ok, just leave !" actionListener="#{wizardBean.destroy}"/></p>
    </h:form>
</ui:component>